#ifndef ERRORCODES_H
#define ERRORCODES_H

#include "libsocket.h"

#ifdef OS_WINDOWS
    #define SOCKERR_INTR WSAEINTR
    #define SOCKERR_ACCES WSAEACCES
    #define SOCKERR_FAULT WSAEFAULT
    #define SOCKERR_INVAL WSAEINVAL
    #define SOCKERR_MFILE WSAEMFILE

    #define SOCKERR_WOULDBLOCK WSAEWOULDBLOCK
    #define SOCKERR_AGAIN SOCKERR_WOULDBLOCK

    #define SOCKERR_ALREADY WSAEALREADY
    #define SOCKERR_PROTONOSUPPORT WSAEPROTONOSUPPORT
    #define SOCKERR_SOCKTNOSUPPORT WSAESOCKTNOSUPPORT
    #define SOCKERR_ADDRINUSE WSAEADDRINUSE
    #define SOCKERR_NETUNREACH WSAENETUNREACH
    #define SOCKERR_NETDOWN WSAENETDOWN
    #define SOCKERR_NETRESET WSAENETRESET
    #define SOCKERR_CONNRESET WSAECONNRESET
    #define SOCKERR_CONNREFUSED WSAECONNREFUSED
    #define SOCKERR_TIMEDOUT WSAETIMEDOUT
#else
    #include <errno.h>

    #define SOCKERR_INTR EINTR
    #define SOCKERR_ACCES EACCES
    #define SOCKERR_FAULT EFAULT
    #define SOCKERR_INVAL EINVAL
    #define SOCKERR_MFILE EMFILE

    #define SOCKERR_WOULDBLOCK EWOULDBLOCK
    #define SOCKERR_AGAIN SOCKERR_WOULDBLOCK

    #define SOCKERR_ALREADY EALREADY
    #define SOCKERR_PROTONOSUPPORT EPROTONOSUPPORT
    #define SOCKERR_SOCKTNOSUPPORT ESOCKTNOSUPPORT
    #define SOCKERR_ADDRINUSE EADDRINUSE
    #define SOCKERR_NETUNREACH ENETUNREACH
    #define SOCKERR_NETDOWN ENETDOWN
    #define SOCKERR_NETRESET ENETRESET
    #define SOCKERR_CONNRESET ECONNRESET
    #define SOCKERR_CONNREFUSED ECONNREFUSED
    #define SOCKERR_TIMEDOUT ETIMEDOUT
#endif

#endif