#ifndef ERRORCODES_H
#define ERRORCODES_H

#include "libsocket.h"

#define CUSTOMERR_STARTOFFSET -1024
#define CUSTOMERR_STEP -1
#define CUSTOMERR(index) (CUSTOMERR_STARTOFFSET + (CUSTOMERR_STEP) * index)

#ifdef OS_WINDOWS
    #define GETLASTERROR() (WSAGetLastError())
    #define SETLASTERROR(x) (WSASetLastError(x))

    #define SOCKERR_NOMEM WSA_NOT_ENOUGH_MEMORY

    #define SOCKERR_INTR WSAEINTR
    #define SOCKERR_ACCES WSAEACCES
    #define SOCKERR_FAULT WSAEFAULT
    #define SOCKERR_INVAL WSAEINVAL
    #define SOCKERR_MFILE WSAEMFILE
    #define SOCKERR_INPROGRESS WSAEINPROGRESS
    #define SOCKERR_ALREADY WSAEALREADY
    #define SOCKERR_INVDESC WSA_INVALID_HANDLE
    #define SOCKERR_NOSPC CUSTOMERR(2)

    #define SOCKERR_AGAIN CUSTOMERR(1)
    #define SOCKERR_WOULDBLOCK WSAEWOULDBLOCK

    #define SOCKERR_AFNOSUPPORT WSAEAFNOSUPPORT
    #define SOCKERR_PROTONOSUPPORT WSAEPROTONOSUPPORT
    #define SOCKERR_SOCKTNOSUPPORT WSAESOCKTNOSUPPORT
    #define SOCKERR_ADDRINUSE WSAEADDRINUSE

    #define SOCKERR_NETUNREACH WSAENETUNREACH
    #define SOCKERR_NETDOWN WSAENETDOWN
    #define SOCKERR_NETRESET WSAENETRESET

    #define SOCKERR_CONNRESET WSAECONNRESET
    #define SOCKERR_CONNREFUSED WSAECONNREFUSED
    #define SOCKERR_TIMEDOUT WSAETIMEDOUT
    #define SOCKERR_NOTCONN WSAENOTCONN
#else
    #include <errno.h>

    #define GETLASTERROR() (errno)
    #define SETLASTERROR(x) (errno = x)

    #define SOCKERR_NOMEM ENOMEM

    #define SOCKERR_INTR EINTR
    #define SOCKERR_ACCES EACCES
    #define SOCKERR_FAULT EFAULT
    #define SOCKERR_INVAL EINVAL
    #define SOCKERR_MFILE EMFILE
    #define SOCKERR_INPROGRESS EINPROGRESS
    #define SOCKERR_ALREADY EALREADY
    #define SOCKERR_INVDESC EBADF
    #define SOCKERR_NOSPC ENOSPC

    #define SOCKERR_WOULDBLOCK EWOULDBLOCK
    #define SOCKERR_AGAIN EAGAIN

    #define SOCKERR_AFNOSUPPORT EAFNOSUPPORT
    #define SOCKERR_PROTONOSUPPORT EPROTONOSUPPORT
    #define SOCKERR_SOCKTNOSUPPORT ESOCKTNOSUPPORT
    #define SOCKERR_ADDRINUSE EADDRINUSE

    #define SOCKERR_NETUNREACH ENETUNREACH
    #define SOCKERR_NETDOWN ENETDOWN
    #define SOCKERR_NETRESET ENETRESET

    #define SOCKERR_CONNRESET ECONNRESET
    #define SOCKERR_CONNREFUSED ECONNREFUSED
    #define SOCKERR_TIMEDOUT ETIMEDOUT
    #define SOCKERR_NOTCONN ENOTCONN
#endif

#define SOCKERR_PARSEADDRFAIL CUSTOMERR(0)

#endif
