/*
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at https://mozilla.org/MPL/2.0/.
*/

#ifndef ERR_H
#define ERR_H

#include "libsocket.h"

#ifdef LIBSOCKET_OS_WINDOWS
    #define GETLASTERROR() (WSAGetLastError())

    #define SOCKERR_INTR WSAEINTR
    #define SOCKERR_ACCES WSAEACCES
    #define SOCKERR_FAULT WSAEFAULT
    #define SOCKERR_INVAL WSAEINVAL
    #define SOCKERR_MFILE WSAEMFILE
    #define SOCKERR_INPROGRESS WSAEINPROGRESS
    #define SOCKERR_ALREADY WSAEALREADY
    #define SOCKERR_INVDESC WSA_INVALID_HANDLE
    #define SOCKERR_NOTSOCK WSAENOTSOCK
    #define SOCKERR_OPNOTSUPP WSAEOPNOTSUPP
    #define SOCKERR_NOBUFFS WSAENOBUFS
    #define SOCKERR_LOOP WSAELOOP
    #define SOCKERR_NAMETOOLONG WSAENAMETOOLONG
    #define SOCKERR_NOMEM WSA_NOT_ENOUGH_MEMORY
    #define SOCKERR_PROCLIM WSAEPROCLIM

    #define SOCKERR_WOULDBLOCK WSAEWOULDBLOCK

    #define SOCKERR_ADDRINUSE WSAEADDRINUSE
    #define SOCKERR_ADDRNOTAVAIL WSAEADDRNOTAVAIL
    #define SOCKERR_DESTADDRREQ WSAEDESTADDRREQ

    #define SOCKERR_AFNOSUPPORT WSAEAFNOSUPPORT
    #define SOCKERR_PROTONOSUPPORT WSAEPROTONOSUPPORT
    #define SOCKERR_SOCKTNOSUPPORT WSAESOCKTNOSUPPORT
    #define SOCKERR_NOPROTOOPT WSAENOPROTOOPT

    #define SOCKERR_NETUNREACH WSAENETUNREACH
    #define SOCKERR_NETDOWN WSAENETDOWN
    #define SOCKERR_NETRESET WSAENETRESET

    #define SOCKERR_CONNRESET WSAECONNRESET
    #define SOCKERR_CONNREFUSED WSAECONNREFUSED
    #define SOCKERR_CONNABORTED WSAECONNABORTED
    #define SOCKERR_TIMEDOUT WSAETIMEDOUT
    #define SOCKERR_NOTCONN WSAENOTCONN
    #define SOCKERR_ISCONN WSAEISCONN
#else
    #include <errno.h>

    #define GETLASTERROR() (errno)

    #define SOCKERR_INTR EINTR
    #define SOCKERR_ACCES EACCES
    #define SOCKERR_FAULT EFAULT
    #define SOCKERR_INVAL EINVAL
    #define SOCKERR_MFILE EMFILE
    #define SOCKERR_INPROGRESS EINPROGRESS
    #define SOCKERR_ALREADY EALREADY
    #define SOCKERR_INVDESC EBADF
    #define SOCKERR_NOSPC ENOSPC
    #define SOCKERR_NOTSOCK ENOTSOCK
    #define SOCKERR_OPNOTSUPP EOPNOTSUPP
    #define SOCKERR_NOBUFFS ENOBUFS
    #define SOCKERR_LOOP ELOOP
    #define SOCKERR_NAMETOOLONG ENAMETOOLONG
    #define SOCKERR_NOMEM ENOMEM

    #ifdef EPROCLIM
        #define SOCKERR_PROCLIM EPROCLIM
    #endif

    #define SOCKERR_WOULDBLOCK EWOULDBLOCK

    #define SOCKERR_ADDRINUSE EADDRINUSE
    #define SOCKERR_ADDRNOTAVAIL EADDRNOTAVAIL
    #define SOCKERR_DESTADDRREQ EDESTADDRREQ

    #define SOCKERR_AFNOSUPPORT EAFNOSUPPORT
    #define SOCKERR_PROTONOSUPPORT EPROTONOSUPPORT
    #define SOCKERR_SOCKTNOSUPPORT ESOCKTNOSUPPORT
    #define SOCKERR_NOPROTOOPT ENOPROTOOPT

    #define SOCKERR_NETUNREACH ENETUNREACH
    #define SOCKERR_NETDOWN ENETDOWN
    #define SOCKERR_NETRESET ENETRESET

    #define SOCKERR_CONNRESET ECONNRESET
    #define SOCKERR_CONNREFUSED ECONNREFUSED
    #define SOCKERR_CONNABORTED ECONNABORTED
    #define SOCKERR_TIMEDOUT ETIMEDOUT
    #define SOCKERR_NOTCONN ENOTCONN
    #define SOCKERR_ISCONN EISCONN
#endif

NError __libsocket_translateerror(int err);
#define translateerror(...) (__libsocket_translateerror(__VA_ARGS__))

#define GETLASTTRANSLATEDSYSERR() (translateerror(GETLASTERROR()))

#endif
